language: go

matrix:
  include:
    - go: 1.13.x
      env: GO111MODULE=on

# Services required
services:
  - redis-server

# Before we run scripts
before_script:
  - go get -u golang.org/x/lint/golint

# Run scripts in parallel
script:
  - golint
  - go vet
  - go test -v

after_success:
  - bash <(curl -s https://codecov.io/bash)